### ISSUE TITLE
nginx default configuration

### ISSUE THREAD

**Issue by jellebreuer** [technivore/ansible-django#1]
This playbook works great but when i first tried it i had to remove the default nginx configiuration 
at /etc/nginx/sites-enabled to remove the standard nginx welcome page.

Also i had to chmod u+x the manage.py file for collectstatic and migrate to work

**Comment by mrichnu** [comment]
Thanks. Which OS are you using?

**Comment by jellebreuer** [comment]
Ubuntu Server 14.04 LTS (HVM)

**Comment by mrichnu** [comment]
This is now fixed in commit https://github.com/technivore/ansible-django/commit/a8ec8bf93c990eb4d4444c74728774b6307dcd63, thank you!
